title: The Giant Refactor
author: Manos Fountoulakis
email: fountoulakismanos@gmail.com
description: The Giant Refactor is a blog about Rails, Stripe, Js and application development.
baseurl: "/manos" # the subpath of your site, e.g. /blog
url: "http://mfountoulakis.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5

# Build settings
# Syntax highlighting
markdown: kramdown
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - .nojekyll
exclude:
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
gems:
 - "jekyll-paginate"
 - "jekyll-gist"
 - jekyll-seo-tag
