title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/manos" # the subpath of your site, e.g. /blog
url: "http://mfountoulakis.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5

# Build settings
# Syntax highlighting
markdown: kramdown
highligher: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - .nojekyll
exclude:
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
gems:
 - "jekyll-paginate"
 - "jekyll-gist"
